#!/bin/bash

# Скрипт для автоматического подключения к серверу
SERVER="root@45.142.122.145"
PASSWORD="W5AV!54uq@5EMXLA"

# Используем expect для автоматического ввода пароля
expect << EOF
spawn ssh $SERVER
expect "password:"
send "$PASSWORD\r"
expect "$"
send "cd /opt/trendpulse-ai\r"
expect "$"
send "ls -la\r"
expect "$"
send "cat > .env << 'EOF'\r"
expect "$"
send "# Telegram Bot Token\r"
expect "$"
send "BOT_TOKEN=7997361131:AAHPvGAAAxwgu5RxQaUOoOvZT79Ig-u3_4w\r"
expect "$"
send "\r"
expect "$"
send "# База данных\r"
expect "$"
send "DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/trendpulse\r"
expect "$"
send "\r"
expect "$"
send "# Окружение\r"
expect "$"
send "ENVIRONMENT=production\r"
expect "$"
send "\r"
expect "$"
send "# API URL (для бота)\r"
expect "$"
send "API_URL=http://backend:8000\r"
expect "$"
send "EOF\r"
expect "$"
send "docker-compose down\r"
expect "$"
send "docker system prune -f\r"
expect "$"
send "docker-compose up --build -d\r"
expect "$"
send "docker-compose ps\r"
expect "$"
send "docker-compose logs -f\r"
interact
EOF 